version: "2"
services:
    cuda8.0-cudnn5:
        image: odanado/miniconda-nvidia-docker:cuda8.0-cudnn5
        build:
            context: .
            args:
                cuda_version: 8.0
                cudnn_version: 5
                python_version: 3.5

    cuda8.0-cudnn6:
        image: odanado/miniconda-nvidia-docker:cuda8.0-cudnn6
        build:
            context: .
            args:
                cuda_version: 8.0
                cudnn_version: 6
                python_version: 3.5

    cuda8.0-cudnn5-py2:
        image: odanado/miniconda-nvidia-docker:cuda8.0-cudnn5-py2
        build:
            context: .
            args:
                cuda_version: 8.0
                cudnn_version: 5
                python_version: 2.7

    cuda8.0-cudnn6-py2:
        image: odanado/miniconda-nvidia-docker:cuda8.0-cudnn6-py2
        build:
            context: .
            args:
                cuda_version: 8.0
                cudnn_version: 6
                python_version: 2.7
